CREATE TABLE "activities" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"external_strava_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"type" text,
	"sport_type" text,
	"workout_type" integer,
	"distance" double precision,
	"moving_time" integer,
	"elapsed_time" integer,
	"total_elevation_gain" real,
	"average_speed" real,
	"max_speed" real,
	"average_heartrate" real,
	"max_heartrate" integer,
	"average_cadence" real,
	"average_watts" real,
	"max_watts" integer,
	"weighted_average_watts" integer,
	"kilojoules" real,
	"calories" real,
	"device_watts" boolean,
	"has_heartrate" boolean,
	"elev_high" real,
	"elev_low" real,
	"average_temp" real,
	"timezone" text,
	"start_date" timestamp,
	"start_date_local" timestamp,
	"polyline" text,
	"summary_polyline" text,
	"start_latlng" jsonb,
	"end_latlng" jsonb,
	"pr_count" integer,
	"suffer_score" integer,
	"achievement_count" integer,
	"gear_id" text,
	"device_name" text,
	"trainer" boolean,
	"commute" boolean,
	"manual" boolean,
	"private" boolean,
	"flagged" boolean,
	"splits_metric" jsonb,
	"strava_laps" jsonb,
	"best_efforts" jsonb,
	"segment_efforts" jsonb,
	"heartrate_stream" jsonb,
	"cadence_stream" jsonb,
	"watts_stream" jsonb,
	"velocity_stream" jsonb,
	"altitude_stream" jsonb,
	"distance_stream" jsonb,
	"time_stream" jsonb,
	"latlng_stream" jsonb,
	"grade_stream" jsonb,
	"temp_stream" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "activities_external_strava_id_idx" ON "activities" USING btree ("external_strava_id");